// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tcc2.portal.domain;

import org.springframework.beans.factory.annotation.Configurable;
import tcc2.portal.domain.Usuario;

privileged aspect Usuario_Roo_Configurable {
    
    declare @type: Usuario: @Configurable;
    
}
